// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6YtPvBMNIF7-Wc76YoGPc4Skbe7r5ewU',
    appId: '1:869319262185:web:0affabb1e6f4920fa41578',
    messagingSenderId: '869319262185',
    projectId: 'sl-explorer',
    authDomain: 'sl-explorer.firebaseapp.com',
    storageBucket: 'sl-explorer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMcyEQ4dHWWWoi_AReovD2bczcUIFfu1E',
    appId: '1:869319262185:android:3f37413957b7c6f2a41578',
    messagingSenderId: '869319262185',
    projectId: 'sl-explorer',
    storageBucket: 'sl-explorer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9lYGorzhpKrD6V36A1ExcgFSpD91HmIs',
    appId: '1:869319262185:ios:4a4773ec229743dea41578',
    messagingSenderId: '869319262185',
    projectId: 'sl-explorer',
    storageBucket: 'sl-explorer.appspot.com',
    iosBundleId: 'com.example.finalReg',
  );
}
