on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

name: "Build & Release App"

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SetUp Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: SetUp Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
 
      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/flutter-apk/app-release.apk'
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN}}